#ifndef SACN_CONSTANTS_LUMINARY_H
#define SACN_CONSTANTS_LUMINARY_H

#include "e131.h"

#define LUMINARY_SACN_PORT               E131_DEFAULT_PORT
#define LUMINARY_SACN_MULTICAST_UNIVERSE 1

#define N_CHANNELS 26 // 0 is unused

#define CHANNEL_M_MODE         1

#define CHANNEL_M_INTENSITY    2
#define CHANNEL_M_COLOR        3
#define CHANNEL_M_PATTERN      4
#define CHANNEL_M_TRANSITION   5

#define CHANNEL_PETALS_BASE    6
#define CHANNEL_PETALS_EACH    4

#define CHANNEL_PETAL_INTENSITY(ii)  (0 + CHANNEL_PETALS_BASE + ii*CHANNEL_PETALS_EACH)
#define CHANNEL_PETAL_COLOR(ii)      (1 + CHANNEL_PETALS_BASE + ii*CHANNEL_PETALS_EACH)
#define CHANNEL_PETAL_PATTERN(ii)    (2 + CHANNEL_PETALS_BASE + ii*CHANNEL_PETALS_EACH)
#define CHANNEL_PETAL_TRANSITION(ii) (3 + CHANNEL_PETALS_BASE + ii*CHANNEL_PETALS_EACH)

#define LUMINARY_SACN_VERBOSE

#endif /* SACN_CONSTANTS_LUMINARY */