#ifndef SACN_CONSTANTS_LUMINARY_H
#define SACN_CONSTANTS_LUMINARY_H

#define N_CHANNELS 5 // 0 is unused

#define CHANNEL_M_MODE 1
#define CHANNEL_M_INTENSITY 2
#define CHANNEL_M_COLOR 3
#define CHANNEL_M_PATTERN 4

#endif /* SACN_CONSTANTS_LUMINARY */